name: Building docker image to test if stuff works
on:
  push:
    branches: [ "dev", "dev/*", "init/*", "hotfix/*", "feat/*", "fix/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build . --file Dockerfile
